// The parts of lnd's RPC the donations guard uses, copied field for field
// from lnd's lnrpc/lightning.proto and lnrpc/walletrpc/walletkit.proto
// (lnd 0.21). Fields the guard only needs to see set, never read (a
// funding shim), are declared as bytes: an embedded message has the same
// wire form. Generate with:
//
//   protoc --go_out=. --go_opt=paths=source_relative lnrpc.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: lnrpc.proto

package lnrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCMiddlewareRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequestId             uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RawMacaroon           []byte                 `protobuf:"bytes,2,opt,name=raw_macaroon,json=rawMacaroon,proto3" json:"raw_macaroon,omitempty"`
	CustomCaveatCondition string                 `protobuf:"bytes,3,opt,name=custom_caveat_condition,json=customCaveatCondition,proto3" json:"custom_caveat_condition,omitempty"`
	// Types that are valid to be assigned to InterceptType:
	//
	//	*RPCMiddlewareRequest_StreamAuth
	//	*RPCMiddlewareRequest_Request
	//	*RPCMiddlewareRequest_Response
	//	*RPCMiddlewareRequest_RegComplete
	InterceptType isRPCMiddlewareRequest_InterceptType `protobuf_oneof:"intercept_type"`
	MsgId         uint64                               `protobuf:"varint,7,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MetadataPairs map[string]*MetadataValues           `protobuf:"bytes,9,rep,name=metadata_pairs,json=metadataPairs,proto3" json:"metadata_pairs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCMiddlewareRequest) Reset() {
	*x = RPCMiddlewareRequest{}
	mi := &file_lnrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCMiddlewareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCMiddlewareRequest) ProtoMessage() {}

func (x *RPCMiddlewareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCMiddlewareRequest.ProtoReflect.Descriptor instead.
func (*RPCMiddlewareRequest) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{0}
}

func (x *RPCMiddlewareRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RPCMiddlewareRequest) GetRawMacaroon() []byte {
	if x != nil {
		return x.RawMacaroon
	}
	return nil
}

func (x *RPCMiddlewareRequest) GetCustomCaveatCondition() string {
	if x != nil {
		return x.CustomCaveatCondition
	}
	return ""
}

func (x *RPCMiddlewareRequest) GetInterceptType() isRPCMiddlewareRequest_InterceptType {
	if x != nil {
		return x.InterceptType
	}
	return nil
}

func (x *RPCMiddlewareRequest) GetStreamAuth() *StreamAuth {
	if x != nil {
		if x, ok := x.InterceptType.(*RPCMiddlewareRequest_StreamAuth); ok {
			return x.StreamAuth
		}
	}
	return nil
}

func (x *RPCMiddlewareRequest) GetRequest() *RPCMessage {
	if x != nil {
		if x, ok := x.InterceptType.(*RPCMiddlewareRequest_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *RPCMiddlewareRequest) GetResponse() *RPCMessage {
	if x != nil {
		if x, ok := x.InterceptType.(*RPCMiddlewareRequest_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *RPCMiddlewareRequest) GetRegComplete() bool {
	if x != nil {
		if x, ok := x.InterceptType.(*RPCMiddlewareRequest_RegComplete); ok {
			return x.RegComplete
		}
	}
	return false
}

func (x *RPCMiddlewareRequest) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *RPCMiddlewareRequest) GetMetadataPairs() map[string]*MetadataValues {
	if x != nil {
		return x.MetadataPairs
	}
	return nil
}

type isRPCMiddlewareRequest_InterceptType interface {
	isRPCMiddlewareRequest_InterceptType()
}

type RPCMiddlewareRequest_StreamAuth struct {
	StreamAuth *StreamAuth `protobuf:"bytes,4,opt,name=stream_auth,json=streamAuth,proto3,oneof"`
}

type RPCMiddlewareRequest_Request struct {
	Request *RPCMessage `protobuf:"bytes,5,opt,name=request,proto3,oneof"`
}

type RPCMiddlewareRequest_Response struct {
	Response *RPCMessage `protobuf:"bytes,6,opt,name=response,proto3,oneof"`
}

type RPCMiddlewareRequest_RegComplete struct {
	RegComplete bool `protobuf:"varint,8,opt,name=reg_complete,json=regComplete,proto3,oneof"`
}

func (*RPCMiddlewareRequest_StreamAuth) isRPCMiddlewareRequest_InterceptType() {}

func (*RPCMiddlewareRequest_Request) isRPCMiddlewareRequest_InterceptType() {}

func (*RPCMiddlewareRequest_Response) isRPCMiddlewareRequest_InterceptType() {}

func (*RPCMiddlewareRequest_RegComplete) isRPCMiddlewareRequest_InterceptType() {}

type MetadataValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataValues) Reset() {
	*x = MetadataValues{}
	mi := &file_lnrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValues) ProtoMessage() {}

func (x *MetadataValues) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValues.ProtoReflect.Descriptor instead.
func (*MetadataValues) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type StreamAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MethodFullUri string                 `protobuf:"bytes,1,opt,name=method_full_uri,json=methodFullUri,proto3" json:"method_full_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAuth) Reset() {
	*x = StreamAuth{}
	mi := &file_lnrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAuth) ProtoMessage() {}

func (x *StreamAuth) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAuth.ProtoReflect.Descriptor instead.
func (*StreamAuth) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{2}
}

func (x *StreamAuth) GetMethodFullUri() string {
	if x != nil {
		return x.MethodFullUri
	}
	return ""
}

type RPCMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MethodFullUri string                 `protobuf:"bytes,1,opt,name=method_full_uri,json=methodFullUri,proto3" json:"method_full_uri,omitempty"`
	StreamRpc     bool                   `protobuf:"varint,2,opt,name=stream_rpc,json=streamRpc,proto3" json:"stream_rpc,omitempty"`
	TypeName      string                 `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Serialized    []byte                 `protobuf:"bytes,4,opt,name=serialized,proto3" json:"serialized,omitempty"`
	IsError       bool                   `protobuf:"varint,5,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCMessage) Reset() {
	*x = RPCMessage{}
	mi := &file_lnrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCMessage) ProtoMessage() {}

func (x *RPCMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCMessage.ProtoReflect.Descriptor instead.
func (*RPCMessage) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{3}
}

func (x *RPCMessage) GetMethodFullUri() string {
	if x != nil {
		return x.MethodFullUri
	}
	return ""
}

func (x *RPCMessage) GetStreamRpc() bool {
	if x != nil {
		return x.StreamRpc
	}
	return false
}

func (x *RPCMessage) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *RPCMessage) GetSerialized() []byte {
	if x != nil {
		return x.Serialized
	}
	return nil
}

func (x *RPCMessage) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type RPCMiddlewareResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RefMsgId uint64                 `protobuf:"varint,1,opt,name=ref_msg_id,json=refMsgId,proto3" json:"ref_msg_id,omitempty"`
	// Types that are valid to be assigned to MiddlewareMessage:
	//
	//	*RPCMiddlewareResponse_Register
	//	*RPCMiddlewareResponse_Feedback
	MiddlewareMessage isRPCMiddlewareResponse_MiddlewareMessage `protobuf_oneof:"middleware_message"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RPCMiddlewareResponse) Reset() {
	*x = RPCMiddlewareResponse{}
	mi := &file_lnrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCMiddlewareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCMiddlewareResponse) ProtoMessage() {}

func (x *RPCMiddlewareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCMiddlewareResponse.ProtoReflect.Descriptor instead.
func (*RPCMiddlewareResponse) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{4}
}

func (x *RPCMiddlewareResponse) GetRefMsgId() uint64 {
	if x != nil {
		return x.RefMsgId
	}
	return 0
}

func (x *RPCMiddlewareResponse) GetMiddlewareMessage() isRPCMiddlewareResponse_MiddlewareMessage {
	if x != nil {
		return x.MiddlewareMessage
	}
	return nil
}

func (x *RPCMiddlewareResponse) GetRegister() *MiddlewareRegistration {
	if x != nil {
		if x, ok := x.MiddlewareMessage.(*RPCMiddlewareResponse_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *RPCMiddlewareResponse) GetFeedback() *InterceptFeedback {
	if x != nil {
		if x, ok := x.MiddlewareMessage.(*RPCMiddlewareResponse_Feedback); ok {
			return x.Feedback
		}
	}
	return nil
}

type isRPCMiddlewareResponse_MiddlewareMessage interface {
	isRPCMiddlewareResponse_MiddlewareMessage()
}

type RPCMiddlewareResponse_Register struct {
	Register *MiddlewareRegistration `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type RPCMiddlewareResponse_Feedback struct {
	Feedback *InterceptFeedback `protobuf:"bytes,3,opt,name=feedback,proto3,oneof"`
}

func (*RPCMiddlewareResponse_Register) isRPCMiddlewareResponse_MiddlewareMessage() {}

func (*RPCMiddlewareResponse_Feedback) isRPCMiddlewareResponse_MiddlewareMessage() {}

type MiddlewareRegistration struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MiddlewareName           string                 `protobuf:"bytes,1,opt,name=middleware_name,json=middlewareName,proto3" json:"middleware_name,omitempty"`
	CustomMacaroonCaveatName string                 `protobuf:"bytes,2,opt,name=custom_macaroon_caveat_name,json=customMacaroonCaveatName,proto3" json:"custom_macaroon_caveat_name,omitempty"`
	ReadOnlyMode             bool                   `protobuf:"varint,3,opt,name=read_only_mode,json=readOnlyMode,proto3" json:"read_only_mode,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MiddlewareRegistration) Reset() {
	*x = MiddlewareRegistration{}
	mi := &file_lnrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareRegistration) ProtoMessage() {}

func (x *MiddlewareRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareRegistration.ProtoReflect.Descriptor instead.
func (*MiddlewareRegistration) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{5}
}

func (x *MiddlewareRegistration) GetMiddlewareName() string {
	if x != nil {
		return x.MiddlewareName
	}
	return ""
}

func (x *MiddlewareRegistration) GetCustomMacaroonCaveatName() string {
	if x != nil {
		return x.CustomMacaroonCaveatName
	}
	return ""
}

func (x *MiddlewareRegistration) GetReadOnlyMode() bool {
	if x != nil {
		return x.ReadOnlyMode
	}
	return false
}

type InterceptFeedback struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Error                 string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ReplaceResponse       bool                   `protobuf:"varint,2,opt,name=replace_response,json=replaceResponse,proto3" json:"replace_response,omitempty"`
	ReplacementSerialized []byte                 `protobuf:"bytes,3,opt,name=replacement_serialized,json=replacementSerialized,proto3" json:"replacement_serialized,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InterceptFeedback) Reset() {
	*x = InterceptFeedback{}
	mi := &file_lnrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptFeedback) ProtoMessage() {}

func (x *InterceptFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptFeedback.ProtoReflect.Descriptor instead.
func (*InterceptFeedback) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{6}
}

func (x *InterceptFeedback) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InterceptFeedback) GetReplaceResponse() bool {
	if x != nil {
		return x.ReplaceResponse
	}
	return false
}

func (x *InterceptFeedback) GetReplacementSerialized() []byte {
	if x != nil {
		return x.ReplacementSerialized
	}
	return nil
}

type OutPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxidBytes     []byte                 `protobuf:"bytes,1,opt,name=txid_bytes,json=txidBytes,proto3" json:"txid_bytes,omitempty"`
	TxidStr       string                 `protobuf:"bytes,2,opt,name=txid_str,json=txidStr,proto3" json:"txid_str,omitempty"`
	OutputIndex   uint32                 `protobuf:"varint,3,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutPoint) Reset() {
	*x = OutPoint{}
	mi := &file_lnrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutPoint) ProtoMessage() {}

func (x *OutPoint) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutPoint.ProtoReflect.Descriptor instead.
func (*OutPoint) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{7}
}

func (x *OutPoint) GetTxidBytes() []byte {
	if x != nil {
		return x.TxidBytes
	}
	return nil
}

func (x *OutPoint) GetTxidStr() string {
	if x != nil {
		return x.TxidStr
	}
	return ""
}

func (x *OutPoint) GetOutputIndex() uint32 {
	if x != nil {
		return x.OutputIndex
	}
	return 0
}

type OpenChannelRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	SatPerVbyte                uint64                 `protobuf:"varint,1,opt,name=sat_per_vbyte,json=satPerVbyte,proto3" json:"sat_per_vbyte,omitempty"`
	NodePubkey                 []byte                 `protobuf:"bytes,2,opt,name=node_pubkey,json=nodePubkey,proto3" json:"node_pubkey,omitempty"`
	NodePubkeyString           string                 `protobuf:"bytes,3,opt,name=node_pubkey_string,json=nodePubkeyString,proto3" json:"node_pubkey_string,omitempty"`
	LocalFundingAmount         int64                  `protobuf:"varint,4,opt,name=local_funding_amount,json=localFundingAmount,proto3" json:"local_funding_amount,omitempty"`
	PushSat                    int64                  `protobuf:"varint,5,opt,name=push_sat,json=pushSat,proto3" json:"push_sat,omitempty"`
	TargetConf                 int32                  `protobuf:"varint,6,opt,name=target_conf,json=targetConf,proto3" json:"target_conf,omitempty"`
	SatPerByte                 int64                  `protobuf:"varint,7,opt,name=sat_per_byte,json=satPerByte,proto3" json:"sat_per_byte,omitempty"`
	Private                    bool                   `protobuf:"varint,8,opt,name=private,proto3" json:"private,omitempty"`
	MinHtlcMsat                int64                  `protobuf:"varint,9,opt,name=min_htlc_msat,json=minHtlcMsat,proto3" json:"min_htlc_msat,omitempty"`
	RemoteCsvDelay             uint32                 `protobuf:"varint,10,opt,name=remote_csv_delay,json=remoteCsvDelay,proto3" json:"remote_csv_delay,omitempty"`
	MinConfs                   int32                  `protobuf:"varint,11,opt,name=min_confs,json=minConfs,proto3" json:"min_confs,omitempty"`
	SpendUnconfirmed           bool                   `protobuf:"varint,12,opt,name=spend_unconfirmed,json=spendUnconfirmed,proto3" json:"spend_unconfirmed,omitempty"`
	CloseAddress               string                 `protobuf:"bytes,13,opt,name=close_address,json=closeAddress,proto3" json:"close_address,omitempty"`
	FundingShim                []byte                 `protobuf:"bytes,14,opt,name=funding_shim,json=fundingShim,proto3" json:"funding_shim,omitempty"`
	RemoteMaxValueInFlightMsat uint64                 `protobuf:"varint,15,opt,name=remote_max_value_in_flight_msat,json=remoteMaxValueInFlightMsat,proto3" json:"remote_max_value_in_flight_msat,omitempty"`
	RemoteMaxHtlcs             uint32                 `protobuf:"varint,16,opt,name=remote_max_htlcs,json=remoteMaxHtlcs,proto3" json:"remote_max_htlcs,omitempty"`
	MaxLocalCsv                uint32                 `protobuf:"varint,17,opt,name=max_local_csv,json=maxLocalCsv,proto3" json:"max_local_csv,omitempty"`
	CommitmentType             int32                  `protobuf:"varint,18,opt,name=commitment_type,json=commitmentType,proto3" json:"commitment_type,omitempty"`
	ZeroConf                   bool                   `protobuf:"varint,19,opt,name=zero_conf,json=zeroConf,proto3" json:"zero_conf,omitempty"`
	ScidAlias                  bool                   `protobuf:"varint,20,opt,name=scid_alias,json=scidAlias,proto3" json:"scid_alias,omitempty"`
	BaseFee                    uint64                 `protobuf:"varint,21,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	FeeRate                    uint64                 `protobuf:"varint,22,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`
	UseBaseFee                 bool                   `protobuf:"varint,23,opt,name=use_base_fee,json=useBaseFee,proto3" json:"use_base_fee,omitempty"`
	UseFeeRate                 bool                   `protobuf:"varint,24,opt,name=use_fee_rate,json=useFeeRate,proto3" json:"use_fee_rate,omitempty"`
	RemoteChanReserveSat       uint64                 `protobuf:"varint,25,opt,name=remote_chan_reserve_sat,json=remoteChanReserveSat,proto3" json:"remote_chan_reserve_sat,omitempty"`
	FundMax                    bool                   `protobuf:"varint,26,opt,name=fund_max,json=fundMax,proto3" json:"fund_max,omitempty"`
	Memo                       string                 `protobuf:"bytes,27,opt,name=memo,proto3" json:"memo,omitempty"`
	Outpoints                  []*OutPoint            `protobuf:"bytes,28,rep,name=outpoints,proto3" json:"outpoints,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *OpenChannelRequest) Reset() {
	*x = OpenChannelRequest{}
	mi := &file_lnrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannelRequest) ProtoMessage() {}

func (x *OpenChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannelRequest.ProtoReflect.Descriptor instead.
func (*OpenChannelRequest) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{8}
}

func (x *OpenChannelRequest) GetSatPerVbyte() uint64 {
	if x != nil {
		return x.SatPerVbyte
	}
	return 0
}

func (x *OpenChannelRequest) GetNodePubkey() []byte {
	if x != nil {
		return x.NodePubkey
	}
	return nil
}

func (x *OpenChannelRequest) GetNodePubkeyString() string {
	if x != nil {
		return x.NodePubkeyString
	}
	return ""
}

func (x *OpenChannelRequest) GetLocalFundingAmount() int64 {
	if x != nil {
		return x.LocalFundingAmount
	}
	return 0
}

func (x *OpenChannelRequest) GetPushSat() int64 {
	if x != nil {
		return x.PushSat
	}
	return 0
}

func (x *OpenChannelRequest) GetTargetConf() int32 {
	if x != nil {
		return x.TargetConf
	}
	return 0
}

func (x *OpenChannelRequest) GetSatPerByte() int64 {
	if x != nil {
		return x.SatPerByte
	}
	return 0
}

func (x *OpenChannelRequest) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *OpenChannelRequest) GetMinHtlcMsat() int64 {
	if x != nil {
		return x.MinHtlcMsat
	}
	return 0
}

func (x *OpenChannelRequest) GetRemoteCsvDelay() uint32 {
	if x != nil {
		return x.RemoteCsvDelay
	}
	return 0
}

func (x *OpenChannelRequest) GetMinConfs() int32 {
	if x != nil {
		return x.MinConfs
	}
	return 0
}

func (x *OpenChannelRequest) GetSpendUnconfirmed() bool {
	if x != nil {
		return x.SpendUnconfirmed
	}
	return false
}

func (x *OpenChannelRequest) GetCloseAddress() string {
	if x != nil {
		return x.CloseAddress
	}
	return ""
}

func (x *OpenChannelRequest) GetFundingShim() []byte {
	if x != nil {
		return x.FundingShim
	}
	return nil
}

func (x *OpenChannelRequest) GetRemoteMaxValueInFlightMsat() uint64 {
	if x != nil {
		return x.RemoteMaxValueInFlightMsat
	}
	return 0
}

func (x *OpenChannelRequest) GetRemoteMaxHtlcs() uint32 {
	if x != nil {
		return x.RemoteMaxHtlcs
	}
	return 0
}

func (x *OpenChannelRequest) GetMaxLocalCsv() uint32 {
	if x != nil {
		return x.MaxLocalCsv
	}
	return 0
}

func (x *OpenChannelRequest) GetCommitmentType() int32 {
	if x != nil {
		return x.CommitmentType
	}
	return 0
}

func (x *OpenChannelRequest) GetZeroConf() bool {
	if x != nil {
		return x.ZeroConf
	}
	return false
}

func (x *OpenChannelRequest) GetScidAlias() bool {
	if x != nil {
		return x.ScidAlias
	}
	return false
}

func (x *OpenChannelRequest) GetBaseFee() uint64 {
	if x != nil {
		return x.BaseFee
	}
	return 0
}

func (x *OpenChannelRequest) GetFeeRate() uint64 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

func (x *OpenChannelRequest) GetUseBaseFee() bool {
	if x != nil {
		return x.UseBaseFee
	}
	return false
}

func (x *OpenChannelRequest) GetUseFeeRate() bool {
	if x != nil {
		return x.UseFeeRate
	}
	return false
}

func (x *OpenChannelRequest) GetRemoteChanReserveSat() uint64 {
	if x != nil {
		return x.RemoteChanReserveSat
	}
	return 0
}

func (x *OpenChannelRequest) GetFundMax() bool {
	if x != nil {
		return x.FundMax
	}
	return false
}

func (x *OpenChannelRequest) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *OpenChannelRequest) GetOutpoints() []*OutPoint {
	if x != nil {
		return x.Outpoints
	}
	return nil
}

type LightningAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightningAddress) Reset() {
	*x = LightningAddress{}
	mi := &file_lnrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightningAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightningAddress) ProtoMessage() {}

func (x *LightningAddress) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightningAddress.ProtoReflect.Descriptor instead.
func (*LightningAddress) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{9}
}

func (x *LightningAddress) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *LightningAddress) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type ConnectPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          *LightningAddress      `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Perm          bool                   `protobuf:"varint,2,opt,name=perm,proto3" json:"perm,omitempty"`
	Timeout       uint64                 `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeerRequest) Reset() {
	*x = ConnectPeerRequest{}
	mi := &file_lnrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeerRequest) ProtoMessage() {}

func (x *ConnectPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeerRequest.ProtoReflect.Descriptor instead.
func (*ConnectPeerRequest) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectPeerRequest) GetAddr() *LightningAddress {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *ConnectPeerRequest) GetPerm() bool {
	if x != nil {
		return x.Perm
	}
	return false
}

func (x *ConnectPeerRequest) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type NewAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAddressRequest) Reset() {
	*x = NewAddressRequest{}
	mi := &file_lnrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddressRequest) ProtoMessage() {}

func (x *NewAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddressRequest.ProtoReflect.Descriptor instead.
func (*NewAddressRequest) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{11}
}

func (x *NewAddressRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *NewAddressRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// walletrpc
type LeaseOutputRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Outpoint               *OutPoint              `protobuf:"bytes,2,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	ExpirationSeconds      uint64                 `protobuf:"varint,3,opt,name=expiration_seconds,json=expirationSeconds,proto3" json:"expiration_seconds,omitempty"`
	ReleaseAfterSpendConfs uint32                 `protobuf:"varint,4,opt,name=release_after_spend_confs,json=releaseAfterSpendConfs,proto3" json:"release_after_spend_confs,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LeaseOutputRequest) Reset() {
	*x = LeaseOutputRequest{}
	mi := &file_lnrpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseOutputRequest) ProtoMessage() {}

func (x *LeaseOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseOutputRequest.ProtoReflect.Descriptor instead.
func (*LeaseOutputRequest) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{12}
}

func (x *LeaseOutputRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *LeaseOutputRequest) GetOutpoint() *OutPoint {
	if x != nil {
		return x.Outpoint
	}
	return nil
}

func (x *LeaseOutputRequest) GetExpirationSeconds() uint64 {
	if x != nil {
		return x.ExpirationSeconds
	}
	return 0
}

func (x *LeaseOutputRequest) GetReleaseAfterSpendConfs() uint32 {
	if x != nil {
		return x.ReleaseAfterSpendConfs
	}
	return 0
}

type ReleaseOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Outpoint      *OutPoint              `protobuf:"bytes,2,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseOutputRequest) Reset() {
	*x = ReleaseOutputRequest{}
	mi := &file_lnrpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseOutputRequest) ProtoMessage() {}

func (x *ReleaseOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lnrpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseOutputRequest.ProtoReflect.Descriptor instead.
func (*ReleaseOutputRequest) Descriptor() ([]byte, []int) {
	return file_lnrpc_proto_rawDescGZIP(), []int{13}
}

func (x *ReleaseOutputRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ReleaseOutputRequest) GetOutpoint() *OutPoint {
	if x != nil {
		return x.Outpoint
	}
	return nil
}

var File_lnrpc_proto protoreflect.FileDescriptor

const file_lnrpc_proto_rawDesc = "" +
	"\n" +
	"\vlnrpc.proto\x12\x05lnrpc\"\xa4\x04\n" +
	"\x14RPCMiddlewareRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12!\n" +
	"\fraw_macaroon\x18\x02 \x01(\fR\vrawMacaroon\x126\n" +
	"\x17custom_caveat_condition\x18\x03 \x01(\tR\x15customCaveatCondition\x124\n" +
	"\vstream_auth\x18\x04 \x01(\v2\x11.lnrpc.StreamAuthH\x00R\n" +
	"streamAuth\x12-\n" +
	"\arequest\x18\x05 \x01(\v2\x11.lnrpc.RPCMessageH\x00R\arequest\x12/\n" +
	"\bresponse\x18\x06 \x01(\v2\x11.lnrpc.RPCMessageH\x00R\bresponse\x12#\n" +
	"\freg_complete\x18\b \x01(\bH\x00R\vregComplete\x12\x15\n" +
	"\x06msg_id\x18\a \x01(\x04R\x05msgId\x12U\n" +
	"\x0emetadata_pairs\x18\t \x03(\v2..lnrpc.RPCMiddlewareRequest.MetadataPairsEntryR\rmetadataPairs\x1aW\n" +
	"\x12MetadataPairsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.lnrpc.MetadataValuesR\x05value:\x028\x01B\x10\n" +
	"\x0eintercept_type\"(\n" +
	"\x0eMetadataValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"4\n" +
	"\n" +
	"StreamAuth\x12&\n" +
	"\x0fmethod_full_uri\x18\x01 \x01(\tR\rmethodFullUri\"\xab\x01\n" +
	"\n" +
	"RPCMessage\x12&\n" +
	"\x0fmethod_full_uri\x18\x01 \x01(\tR\rmethodFullUri\x12\x1d\n" +
	"\n" +
	"stream_rpc\x18\x02 \x01(\bR\tstreamRpc\x12\x1b\n" +
	"\ttype_name\x18\x03 \x01(\tR\btypeName\x12\x1e\n" +
	"\n" +
	"serialized\x18\x04 \x01(\fR\n" +
	"serialized\x12\x19\n" +
	"\bis_error\x18\x05 \x01(\bR\aisError\"\xc0\x01\n" +
	"\x15RPCMiddlewareResponse\x12\x1c\n" +
	"\n" +
	"ref_msg_id\x18\x01 \x01(\x04R\brefMsgId\x12;\n" +
	"\bregister\x18\x02 \x01(\v2\x1d.lnrpc.MiddlewareRegistrationH\x00R\bregister\x126\n" +
	"\bfeedback\x18\x03 \x01(\v2\x18.lnrpc.InterceptFeedbackH\x00R\bfeedbackB\x14\n" +
	"\x12middleware_message\"\xa6\x01\n" +
	"\x16MiddlewareRegistration\x12'\n" +
	"\x0fmiddleware_name\x18\x01 \x01(\tR\x0emiddlewareName\x12=\n" +
	"\x1bcustom_macaroon_caveat_name\x18\x02 \x01(\tR\x18customMacaroonCaveatName\x12$\n" +
	"\x0eread_only_mode\x18\x03 \x01(\bR\freadOnlyMode\"\x8b\x01\n" +
	"\x11InterceptFeedback\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12)\n" +
	"\x10replace_response\x18\x02 \x01(\bR\x0freplaceResponse\x125\n" +
	"\x16replacement_serialized\x18\x03 \x01(\fR\x15replacementSerialized\"g\n" +
	"\bOutPoint\x12\x1d\n" +
	"\n" +
	"txid_bytes\x18\x01 \x01(\fR\ttxidBytes\x12\x19\n" +
	"\btxid_str\x18\x02 \x01(\tR\atxidStr\x12!\n" +
	"\foutput_index\x18\x03 \x01(\rR\voutputIndex\"\x98\b\n" +
	"\x12OpenChannelRequest\x12\"\n" +
	"\rsat_per_vbyte\x18\x01 \x01(\x04R\vsatPerVbyte\x12\x1f\n" +
	"\vnode_pubkey\x18\x02 \x01(\fR\n" +
	"nodePubkey\x12,\n" +
	"\x12node_pubkey_string\x18\x03 \x01(\tR\x10nodePubkeyString\x120\n" +
	"\x14local_funding_amount\x18\x04 \x01(\x03R\x12localFundingAmount\x12\x19\n" +
	"\bpush_sat\x18\x05 \x01(\x03R\apushSat\x12\x1f\n" +
	"\vtarget_conf\x18\x06 \x01(\x05R\n" +
	"targetConf\x12 \n" +
	"\fsat_per_byte\x18\a \x01(\x03R\n" +
	"satPerByte\x12\x18\n" +
	"\aprivate\x18\b \x01(\bR\aprivate\x12\"\n" +
	"\rmin_htlc_msat\x18\t \x01(\x03R\vminHtlcMsat\x12(\n" +
	"\x10remote_csv_delay\x18\n" +
	" \x01(\rR\x0eremoteCsvDelay\x12\x1b\n" +
	"\tmin_confs\x18\v \x01(\x05R\bminConfs\x12+\n" +
	"\x11spend_unconfirmed\x18\f \x01(\bR\x10spendUnconfirmed\x12#\n" +
	"\rclose_address\x18\r \x01(\tR\fcloseAddress\x12!\n" +
	"\ffunding_shim\x18\x0e \x01(\fR\vfundingShim\x12C\n" +
	"\x1fremote_max_value_in_flight_msat\x18\x0f \x01(\x04R\x1aremoteMaxValueInFlightMsat\x12(\n" +
	"\x10remote_max_htlcs\x18\x10 \x01(\rR\x0eremoteMaxHtlcs\x12\"\n" +
	"\rmax_local_csv\x18\x11 \x01(\rR\vmaxLocalCsv\x12'\n" +
	"\x0fcommitment_type\x18\x12 \x01(\x05R\x0ecommitmentType\x12\x1b\n" +
	"\tzero_conf\x18\x13 \x01(\bR\bzeroConf\x12\x1d\n" +
	"\n" +
	"scid_alias\x18\x14 \x01(\bR\tscidAlias\x12\x19\n" +
	"\bbase_fee\x18\x15 \x01(\x04R\abaseFee\x12\x19\n" +
	"\bfee_rate\x18\x16 \x01(\x04R\afeeRate\x12 \n" +
	"\fuse_base_fee\x18\x17 \x01(\bR\n" +
	"useBaseFee\x12 \n" +
	"\fuse_fee_rate\x18\x18 \x01(\bR\n" +
	"useFeeRate\x125\n" +
	"\x17remote_chan_reserve_sat\x18\x19 \x01(\x04R\x14remoteChanReserveSat\x12\x19\n" +
	"\bfund_max\x18\x1a \x01(\bR\afundMax\x12\x12\n" +
	"\x04memo\x18\x1b \x01(\tR\x04memo\x12-\n" +
	"\toutpoints\x18\x1c \x03(\v2\x0f.lnrpc.OutPointR\toutpoints\">\n" +
	"\x10LightningAddress\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\"o\n" +
	"\x12ConnectPeerRequest\x12+\n" +
	"\x04addr\x18\x01 \x01(\v2\x17.lnrpc.LightningAddressR\x04addr\x12\x12\n" +
	"\x04perm\x18\x02 \x01(\bR\x04perm\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x04R\atimeout\"A\n" +
	"\x11NewAddressRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\"\xbb\x01\n" +
	"\x12LeaseOutputRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12+\n" +
	"\boutpoint\x18\x02 \x01(\v2\x0f.lnrpc.OutPointR\boutpoint\x12-\n" +
	"\x12expiration_seconds\x18\x03 \x01(\x04R\x11expirationSeconds\x129\n" +
	"\x19release_after_spend_confs\x18\x04 \x01(\rR\x16releaseAfterSpendConfs\"S\n" +
	"\x14ReleaseOutputRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12+\n" +
	"\boutpoint\x18\x02 \x01(\v2\x0f.lnrpc.OutPointR\boutpoint2c\n" +
	"\tLightning\x12V\n" +
	"\x15RegisterRPCMiddleware\x12\x1c.lnrpc.RPCMiddlewareResponse\x1a\x1b.lnrpc.RPCMiddlewareRequest(\x010\x01BIZGgithub.com/paulscode/lightning-fork-swap/donations/internal/guard/lnrpcb\x06proto3"

var (
	file_lnrpc_proto_rawDescOnce sync.Once
	file_lnrpc_proto_rawDescData []byte
)

func file_lnrpc_proto_rawDescGZIP() []byte {
	file_lnrpc_proto_rawDescOnce.Do(func() {
		file_lnrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lnrpc_proto_rawDesc), len(file_lnrpc_proto_rawDesc)))
	})
	return file_lnrpc_proto_rawDescData
}

var file_lnrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_lnrpc_proto_goTypes = []any{
	(*RPCMiddlewareRequest)(nil),   // 0: lnrpc.RPCMiddlewareRequest
	(*MetadataValues)(nil),         // 1: lnrpc.MetadataValues
	(*StreamAuth)(nil),             // 2: lnrpc.StreamAuth
	(*RPCMessage)(nil),             // 3: lnrpc.RPCMessage
	(*RPCMiddlewareResponse)(nil),  // 4: lnrpc.RPCMiddlewareResponse
	(*MiddlewareRegistration)(nil), // 5: lnrpc.MiddlewareRegistration
	(*InterceptFeedback)(nil),      // 6: lnrpc.InterceptFeedback
	(*OutPoint)(nil),               // 7: lnrpc.OutPoint
	(*OpenChannelRequest)(nil),     // 8: lnrpc.OpenChannelRequest
	(*LightningAddress)(nil),       // 9: lnrpc.LightningAddress
	(*ConnectPeerRequest)(nil),     // 10: lnrpc.ConnectPeerRequest
	(*NewAddressRequest)(nil),      // 11: lnrpc.NewAddressRequest
	(*LeaseOutputRequest)(nil),     // 12: lnrpc.LeaseOutputRequest
	(*ReleaseOutputRequest)(nil),   // 13: lnrpc.ReleaseOutputRequest
	nil,                            // 14: lnrpc.RPCMiddlewareRequest.MetadataPairsEntry
}
var file_lnrpc_proto_depIdxs = []int32{
	2,  // 0: lnrpc.RPCMiddlewareRequest.stream_auth:type_name -> lnrpc.StreamAuth
	3,  // 1: lnrpc.RPCMiddlewareRequest.request:type_name -> lnrpc.RPCMessage
	3,  // 2: lnrpc.RPCMiddlewareRequest.response:type_name -> lnrpc.RPCMessage
	14, // 3: lnrpc.RPCMiddlewareRequest.metadata_pairs:type_name -> lnrpc.RPCMiddlewareRequest.MetadataPairsEntry
	5,  // 4: lnrpc.RPCMiddlewareResponse.register:type_name -> lnrpc.MiddlewareRegistration
	6,  // 5: lnrpc.RPCMiddlewareResponse.feedback:type_name -> lnrpc.InterceptFeedback
	7,  // 6: lnrpc.OpenChannelRequest.outpoints:type_name -> lnrpc.OutPoint
	9,  // 7: lnrpc.ConnectPeerRequest.addr:type_name -> lnrpc.LightningAddress
	7,  // 8: lnrpc.LeaseOutputRequest.outpoint:type_name -> lnrpc.OutPoint
	7,  // 9: lnrpc.ReleaseOutputRequest.outpoint:type_name -> lnrpc.OutPoint
	1,  // 10: lnrpc.RPCMiddlewareRequest.MetadataPairsEntry.value:type_name -> lnrpc.MetadataValues
	4,  // 11: lnrpc.Lightning.RegisterRPCMiddleware:input_type -> lnrpc.RPCMiddlewareResponse
	0,  // 12: lnrpc.Lightning.RegisterRPCMiddleware:output_type -> lnrpc.RPCMiddlewareRequest
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_lnrpc_proto_init() }
func file_lnrpc_proto_init() {
	if File_lnrpc_proto != nil {
		return
	}
	file_lnrpc_proto_msgTypes[0].OneofWrappers = []any{
		(*RPCMiddlewareRequest_StreamAuth)(nil),
		(*RPCMiddlewareRequest_Request)(nil),
		(*RPCMiddlewareRequest_Response)(nil),
		(*RPCMiddlewareRequest_RegComplete)(nil),
	}
	file_lnrpc_proto_msgTypes[4].OneofWrappers = []any{
		(*RPCMiddlewareResponse_Register)(nil),
		(*RPCMiddlewareResponse_Feedback)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lnrpc_proto_rawDesc), len(file_lnrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lnrpc_proto_goTypes,
		DependencyIndexes: file_lnrpc_proto_depIdxs,
		MessageInfos:      file_lnrpc_proto_msgTypes,
	}.Build()
	File_lnrpc_proto = out.File
	file_lnrpc_proto_goTypes = nil
	file_lnrpc_proto_depIdxs = nil
}
